import {beforeEach,it,expect,vi} from 'vitest'
const mock=vi.hoisted(()=>({current:{interests:[] as unknown[],updated_at:'2026-10-01T00:00:00Z'},writes:[] as Record<string,unknown>[],collide:false}))
vi.mock('./clients',()=>({getServiceSupabase:()=>({from:()=>{let mutation:Record<string,unknown>|undefined;const q={select:()=>q,eq:()=>q,update:(v:Record<string,unknown>)=>{mutation=v;return q},insert:(v:Record<string,unknown>)=>{mutation=v;return q},maybeSingle:async()=>{if(!mutation)return {data:mock.current,error:null};mock.writes.push(mutation);if(mock.collide){mock.collide=false;mock.current.interests=[{topic:'Nuova regola',score:100,origin:'manual',mode:'prioritize'}];mock.current.updated_at='2026-10-02T00:00:00Z';return {data:null,error:null}}return {data:{user_id:'owner'},error:null}}};return q}})}))
import {writeEditorial} from './editorial'
beforeEach(()=>{mock.current={interests:[{topic:'Personale',score:70,origin:'manual',mode:'prioritize'},{topic:'Appreso',score:80}],updated_at:'2026-10-01T00:00:00Z'};mock.writes=[];mock.collide=false})
it('preserves manual interests when learned interests are regenerated',async()=>{const result=await writeEditorial('owner',[{topic:'Nuovo appreso',score:90}],null,'learned');expect(result.interests).toMatchObject([{topic:'Nuovo appreso',score:90},{topic:'Personale',score:70,origin:'manual',mode:'prioritize'}])})
it('retries learned writes after a concurrent manual edit without losing it',async()=>{mock.collide=true;const result=await writeEditorial('owner',[{topic:'Appreso',score:70}],null,'learned');expect(mock.writes).toHaveLength(2);expect(result.interests[1]).toMatchObject({topic:'Nuova regola',score:100,origin:'manual',mode:'prioritize'})})
it('rejects stale manual drafts and preserves the newer device edit',async()=>{await expect(writeEditorial('owner',[],null,'manual')).rejects.toThrow('PREFERENCES_CONFLICT');expect(mock.writes).toHaveLength(0)})
it('removes manual rules without resetting learned interests',async()=>{const result=await writeEditorial('owner',[],mock.current.updated_at,'manual');expect(result.interests).toMatchObject([{topic:'Appreso',score:80}])})
