'use client'
import { useRef, useState } from 'react'
import type { Backup } from '@/lib/backup/schema'
type Costs={budget:{enabled:boolean;monthly_limit_microusd:number};measured_microusd:number;uncertain_microusd:number;reserved_microusd:number;attempts:number;tracking_since:string|null;stages:Record<string,number>}
const dollars=(micro:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'USD',minimumFractionDigits:4}).format(micro/1000000)
const labels:Record<string,string>={sources:'Fonti nuove (inizialmente disattivate)',articles:'Articoli',saved:'Salvati',library:'Cartelle, tag e stato letto',feedback:'Preferenze sugli articoli',reader:'Testi nel lettore',interests:'Profilo interessi',budget:'Budget',alerts:'Regole avvisi (inizialmente disattivate)'}
export function CostBackup({onChanged}:{onChanged:()=>Promise<unknown>|void}){
 const [open,setOpen]=useState(false),[data,setData]=useState<Costs|null>(null),[enabled,setEnabled]=useState(false),[limit,setLimit]=useState('5'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[backup,setBackup]=useState<Backup|null>(null),[preview,setPreview]=useState<{counts:Record<string,number>;fingerprint:string}|null>(null)
 const lock=useRef(false),input=useRef<HTMLInputElement>(null)
 async function load(){const response=await fetch('/api/costs',{cache:'no-store'}),value=await response.json();if(!response.ok)throw new Error(value.message);setData(value);setEnabled(value.budget.enabled);setLimit(String(value.budget.monthly_limit_microusd/1000000))}
 async function action(work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{await work()}catch(e){setMessage(e instanceof Error?e.message:'Operazione non riuscita')}finally{lock.current=false;setBusy(false)}}
 async function choose(file?:File){setBackup(null);setPreview(null);if(!file)return;await action(async()=>{if(file.size>3900000)throw new Error('Massimo 3,9 MB per file di backup.');const value=JSON.parse(await file.text());const response=await fetch('/api/backup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({backup:value,apply:false})}),result=await response.json();if(!response.ok)throw new Error(result.message);setBackup(value);setPreview(result)})}
 async function download(){await action(async()=>{const response=await fetch('/api/backup',{cache:'no-store'});if(!response.ok){const value=await response.json();throw new Error(value.message)}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`athena-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Backup esportato. Conservalo per un ripristino futuro.')})}
 return <section className="mb-4 rounded-2xl border border-white/10 bg-white/[0.025] text-sm">
  <button type="button" className="flex min-h-12 w-full items-center justify-between gap-3 px-4 py-3 text-left" aria-expanded={open} onClick={()=>{setOpen(!open);if(!open)void action(load)}}><span>Costi IA e backup</span><span aria-hidden="true">{open?'−':'+'}</span></button>
  {open&&<div className="space-y-4 border-t border-white/10 p-4">
   {data&&<><p><strong>{dollars(data.measured_microusd)}</strong> stimati dai token nel mese UTC · {data.attempts} tentativi</p><p className="text-xs text-white/60">Incerti: {dollars(data.uncertain_microusd)} · Prenotati o in attesa di conferma: {dollars(data.reserved_microusd)}. Monitoraggio {data.tracking_since?`dal ${new Date(data.tracking_since).toLocaleString('it-IT')}`:'attivo dalle prossime richieste'}. I mesi precedenti non sono ricostruiti.</p>
   {Object.keys(data.stages).length>0&&<ul className="text-xs text-white/60">{Object.entries(data.stages).map(([stage,cost])=><li key={stage}>{stage}: {dollars(cost)} (include importi incerti e prenotati)</li>)}</ul>}
   <p className="text-xs text-white/60">Stima delle sole richieste OpenAI di Athena, non della fattura totale né dei costi Vercel/Supabase. <a className="underline" href="https://developers.openai.com/api/docs/models/gpt-4o-mini" target="_blank" rel="noopener noreferrer">Tariffe verificate il 4 ottobre 2026</a>.</p>
   <label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Attiva tetto mensile IA</label>
   <div className="flex flex-wrap items-end gap-3"><label className="flex flex-col gap-1">Tetto in USD<input className="w-32 rounded-lg border border-white/15 bg-black/20 p-2" type="number" min="0.01" max="1000" step="0.01" value={limit} onChange={e=>setLimit(e.target.value)}/></label><button disabled={busy} className="min-h-11 rounded-lg border border-white/15 px-3 disabled:opacity-50" onClick={()=>void action(async()=>{const response=await fetch('/api/costs',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled,monthly_limit_microusd:Math.round(Number(limit)*1000000)})});const value=await response.json();if(!response.ok)throw new Error(value.message);await load();setMessage('Budget salvato. RSS, salvati e audio restano disponibili anche al raggiungimento del tetto.')})}>Salva budget</button></div></>}
   <hr className="border-white/10"/><p>Backup portabile di fonti, interessi, salvati, biblioteca, mi piace e testi già acquisiti.</p><p className="text-xs text-white/60">Esclude password, chiavi API, dispositivi push, cache offline, traduzioni locali, selezioni IA e cronologie degli eventi. Il ripristino aggiunge solo ciò che manca e conserva i valori già presenti. Le nuove fonti e gli avvisi importati si attivano manualmente.</p>
   <div className="flex flex-wrap gap-3"><button disabled={busy} onClick={()=>void download()} className="min-h-11 rounded-lg border border-white/15 px-3 disabled:opacity-50">Esporta backup</button><button disabled={busy} onClick={()=>input.current?.click()} className="min-h-11 rounded-lg border border-white/15 px-3 disabled:opacity-50">Scegli backup</button><input ref={input} className="hidden" type="file" accept="application/json,.json" aria-label="File backup" onChange={e=>{void choose(e.target.files?.[0]);e.target.value=''}}/></div>
   {preview&&<div className="space-y-2 rounded-xl bg-black/20 p-3"><strong>Anteprima ripristino</strong><ul>{Object.entries(labels).map(([key,label])=><li key={key}>{label}: {preview.counts[key]??0}</li>)}</ul><button disabled={busy||!backup} className="min-h-11 rounded-lg border border-white/15 px-3 disabled:opacity-50" onClick={()=>void action(async()=>{const response=await fetch('/api/backup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({backup,apply:true,fingerprint:preview.fingerprint})}),result=await response.json();if(!response.ok)throw new Error(result.message);setPreview(null);setBackup(null);await onChanged();await load();setMessage('Ripristino completato. I dati esistenti sono stati conservati.')})}>Ripristina dati mancanti</button></div>}
   {message&&<p role="status" className="text-xs text-white/80">{message}</p>}
  </div>}
 </section>
}
