'use client'
import { useRef,useState } from 'react'
import type { Interest } from '@/lib/ai/editorial'
import type { Source } from './types'
type Profile={manual:Interest[];learned:Interest[];version:string|null;preview?:{id:string;title:string;source:string;reason:string;score:number}[]}
export function EditorialPreferences({sources,onChanged}:{sources:Source[];onChanged:()=>Promise<unknown>}) {
 const [open,setOpen]=useState(false);const [profile,setProfile]=useState<Profile|null>(null);const [draft,setDraft]=useState<Interest[]>([])
 const [topic,setTopic]=useState('');const [mode,setMode]=useState<'prioritize'|'exclude'>('prioritize');const [score,setScore]=useState(70);const [source,setSource]=useState('')
 const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const lock=useRef(false);const [dirty,setDirty]=useState(false)
 async function request(preview=false) {
  if(lock.current)return;lock.current=true;setBusy(true);setMessage('')
  try {const response=await fetch(`/api/preferences${preview?'?preview=1':''}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.message??'Preferenze non disponibili');setProfile(data);setDraft(data.manual);setDirty(false);if(preview)setMessage('Anteprima aggiornata sulle notizie recenti della home: applica le preferenze salvate senza chiamare l’IA. Le selezioni precedenti restano consultabili.')}catch(error){setMessage(error instanceof Error?error.message:'Caricamento non riuscito')}finally{lock.current=false;setBusy(false)}
 }
 function add(){const name=source?sources.find(s=>s.id===source)?.name:topic.trim();if(!name)return;if(draft.some(i=>source?i.source_id===source:!i.source_id&&i.topic.toLowerCase()===name.toLowerCase())){setMessage('Tema o fonte già presente. Modifica la regola esistente.');return}setDraft(items=>[...items,{topic:name,score:source||mode==='exclude'?0:score,origin:'manual',mode:source?'exclude':mode,...(source?{source_id:source}:{})}]);setTopic('');setSource('');setDirty(true);setMessage('Modifica da salvare.')}
 async function save(){if(lock.current||!profile)return;lock.current=true;setBusy(true);setMessage('');try{const response=await fetch('/api/preferences',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({manual:draft,version:profile.version})});const data=await response.json();if(!response.ok)throw new Error(data.message??'Salvataggio non riuscito');setProfile(data);setDraft(data.manual);setDirty(false);setMessage('Preferenze salvate su tutti i dispositivi. Verifica l’anteprima o ricalcola le scelte IA.');await onChanged().catch(()=>setMessage('Preferenze salvate; ricarica la pagina per aggiornare i dati.'))}catch(error){setMessage(error instanceof Error?error.message:'Salvataggio non riuscito')}finally{lock.current=false;setBusy(false)}}
 const input='min-h-11 w-full rounded-xl border border-white/15 bg-[#111015] p-3 text-sm text-white'
 return <section className="mb-5 rounded-2xl border border-[#B88A44]/20 bg-white/[0.025] p-3 sm:p-5">
  <button className="min-h-11 w-full text-left text-sm text-[#E2C188]" aria-expanded={open} onClick={()=>{setOpen(!open);if(!profile&&!open)void request()}}>Personalizza le scelte {open?'−':'+'}</button>
  {open&&<div className="mt-3 space-y-4">
   <p className="text-xs leading-5 text-neutral-400">I tuoi temi e le esclusioni prevalgono sul profilo appreso. Si applicano alle prossime selezioni in home e nei settori; il feed cronologico conserva tutte le notizie. Le priorità delle testate si modificano in Fonti.</p>
   {profile&&<>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-neutral-300">Tema personale<input className={input} value={topic} maxLength={100} onChange={e=>setTopic(e.target.value)} placeholder="Es. intelligenza artificiale, processo penale" disabled={busy}/></label>
    <label className="text-xs text-neutral-300">Oppure escludi una fonte<select className={input} value={source} onChange={e=>setSource(e.target.value)} disabled={busy}><option value="">Scegli una fonte</option>{sources.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>
    <label className="text-xs text-neutral-300">Regola<select className={input} value={source?'exclude':mode} disabled={busy||Boolean(source)} onChange={e=>setMode(e.target.value as typeof mode)}><option value="prioritize">Dai priorità</option><option value="exclude">Escludi dalle scelte</option></select></label>
    {mode==='prioritize'&&!source&&<label className="text-xs text-neutral-300">Priorità<select className={input} value={score} disabled={busy} onChange={e=>setScore(Number(e.target.value))}><option value={40}>Normale</option><option value={70}>Alta</option><option value={100}>Massima</option></select></label>}</div>
    <button className={input} disabled={busy||(!source&&topic.trim().length<2)||draft.length>=40} onClick={add}>Aggiungi regola</button>
    <div className="space-y-2" aria-label="Regole personali">{draft.length?draft.map((i,index)=><div key={i.source_id??i.topic} className="flex items-center gap-3 rounded-xl bg-black/20 p-3"><div className="min-w-0 flex-1"><p className="break-words text-sm">{i.topic}</p><label className="text-xs text-neutral-400">{i.mode==='exclude'?'Esclusione': 'Priorità'}{i.mode==='prioritize'&&<select aria-label={`Priorità di ${i.topic}`} className="ml-2 rounded border border-white/10 bg-[#111015] p-2" value={i.score} disabled={busy} onChange={e=>{setDraft(items=>items.map((entry,n)=>n===index?{...entry,score:Number(e.target.value)}:entry));setDirty(true)}}><option value={40}>Normale</option><option value={70}>Alta</option><option value={100}>Massima</option>{![40,70,100].includes(i.score)&&<option value={i.score}>{i.score}</option>}</select>}</label></div><button aria-label={`Rimuovi regola ${i.topic}`} disabled={busy} className="min-h-11 px-2 text-sm text-neutral-300 underline" onClick={()=>{setDraft(items=>items.filter((_,n)=>n!==index));setDirty(true)}}>Rimuovi</button></div>):<p className="text-xs text-neutral-400">Nessuna regola personale. Puoi aggiungerne una qui.</p>}</div>
    <div className="grid gap-2 sm:grid-cols-3"><button disabled={busy||!dirty} className={input+' disabled:opacity-40'} onClick={()=>void save()}>Salva preferenze</button><button disabled={busy||dirty} className={input+' disabled:opacity-40'} onClick={()=>void request(true)}>Verifica le mie scelte</button><button disabled={busy} className={input} onClick={()=>void request()}>Ricarica preferenze</button></div>
    {profile.version&&<p className="text-xs text-neutral-400">Profilo aggiornato: <time dateTime={profile.version}>{new Date(profile.version).toLocaleString('it-IT')}</time>{dirty?' · modifiche da salvare':''}</p>}
    <details><summary className="min-h-11 cursor-pointer text-sm text-neutral-300">Interessi appresi dall’IA ({profile.learned.length})</summary><ul className="mt-2 space-y-1 text-xs text-neutral-400">{profile.learned.map(i=><li key={i.topic}>{i.topic} · {i.score}/100</li>)}</ul></details>
    {profile.preview&&<div aria-label="Anteprima delle preferenze"><h3 className="text-sm text-[#E2C188]">Anteprima automatica delle scelte</h3><ol className="mt-3 space-y-3">{profile.preview.map(p=><li key={p.id} className="rounded-xl border border-white/10 p-3 text-sm"><p>{p.title}</p><p className="mt-1 text-xs text-neutral-400">{p.source} · {p.score}/100</p><p className="mt-2 text-xs leading-5 text-neutral-300">{p.reason}</p></li>)}</ol>{!profile.preview.length&&<p className="text-sm">Nessuna notizia disponibile dopo le esclusioni.</p>}</div>}
   </>}
   {busy&&<p role="status" className="text-sm">Operazione in corso…</p>}{message&&<p role="status" className="text-sm leading-6 text-neutral-300">{message}</p>}
  </div>}
 </section>
}
