// @vitest-environment jsdom
import React from 'react'
import {afterEach,it,expect,vi} from 'vitest'
import {cleanup,fireEvent,render,screen} from '@testing-library/react'
import {EditorialPreferences} from './editorial-preferences'
afterEach(()=>{cleanup();vi.unstubAllGlobals()})
it('saves a manual rule with its version and verifies the persisted preview',async()=>{
 const fetch=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({manual:[],learned:[],version:'v1'}))).mockResolvedValueOnce(new Response(JSON.stringify({manual:[{topic:'processo penale',score:70,origin:'manual',mode:'prioritize'}],learned:[],version:'v2'}))).mockResolvedValueOnce(new Response(JSON.stringify({manual:[],learned:[],version:'v2',preview:[{id:'a',title:'Nuova sentenza',source:'Cassazione',reason:'Tema scelto da te',score:90}]})))
 vi.stubGlobal('fetch',fetch);render(<EditorialPreferences sources={[]} onChanged={async()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:/Personalizza/}));await screen.findByText('Nessuna regola personale. Puoi aggiungerne una qui.');fireEvent.change(screen.getByLabelText('Tema personale'),{target:{value:'processo penale'}});fireEvent.click(screen.getByRole('button',{name:'Aggiungi regola'}));fireEvent.click(screen.getByRole('button',{name:'Salva preferenze'}));await screen.findByText(/Preferenze salvate su tutti/);expect(JSON.parse(fetch.mock.calls[1][1].body)).toEqual({version:'v1',manual:[{topic:'processo penale',score:70,origin:'manual',mode:'prioritize'}]});fireEvent.click(screen.getByRole('button',{name:'Verifica le mie scelte'}));expect(await screen.findByText('Nuova sentenza')).toBeTruthy()
})
it('keeps unsaved drafts on write failure rather than claiming persistence',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({manual:[],learned:[],version:null}))).mockResolvedValueOnce(new Response(JSON.stringify({message:'Preferenze cambiate su un altro dispositivo'}),{status:409})));render(<EditorialPreferences sources={[]} onChanged={async()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:/Personalizza/}));await screen.findByText('Nessuna regola personale. Puoi aggiungerne una qui.');fireEvent.change(screen.getByLabelText('Tema personale'),{target:{value:'gaming'}});fireEvent.click(screen.getByRole('button',{name:'Aggiungi regola'}));fireEvent.click(screen.getByRole('button',{name:'Salva preferenze'}));expect(await screen.findByText('Preferenze cambiate su un altro dispositivo')).toBeTruthy();expect(screen.getByText('gaming')).toBeTruthy()})
