// Publisher feeds or official pages advertising feeds. Only live, recent RSS/Atom
// feeds are added; this list is a set of candidates, not a claim of availability.
export const sourceCatalog = [
  { name: 'ANSA · Ultime notizie', site: 'https://www.ansa.it', feed: 'https://www.ansa.it/sito/ansait_rss.xml', topic: 'Attualità italiana' },
  { name: 'Adnkronos', site: 'https://www.adnkronos.com', feed: 'https://www.adnkronos.com/rss', topic: 'Attualità italiana' },
  { name: 'Il Fatto Quotidiano', site: 'https://www.ilfattoquotidiano.it', feed: 'https://www.ilfattoquotidiano.it/feed/', topic: 'Politica e cronaca' },
  { name: 'LiveSicilia', site: 'https://livesicilia.it', feed: 'https://livesicilia.it/feed/', topic: 'Sicilia' },
  { name: 'IlSicilia', site: 'https://ilsicilia.it', feed: 'https://ilsicilia.it/feed/', topic: 'Sicilia' },
  { name: 'CataniaToday', site: 'https://www.cataniatoday.it', feed: 'https://www.cataniatoday.it', topic: 'Catania' },
  { name: 'PalermoToday', site: 'https://www.palermotoday.it', feed: 'https://www.palermotoday.it', topic: 'Palermo' },
  { name: 'BBC · Mondo', site: 'https://www.bbc.com/news', feed: 'https://feeds.bbci.co.uk/news/world/rss.xml', topic: 'Esteri' },
  { name: 'Euronews · Italiano', site: 'https://it.euronews.com', feed: 'https://it.euronews.com/rss?format=mrss&level=theme&name=news', topic: 'Esteri' },
  { name: 'Eunews', site: 'https://www.eunews.it', feed: 'https://www.eunews.it/feed/', topic: 'Unione europea' },
  { name: 'Lavoce.info', site: 'https://lavoce.info', feed: 'https://lavoce.info/feed/', topic: 'Economia' },
  { name: 'ScienceDaily', site: 'https://www.sciencedaily.com', feed: 'https://www.sciencedaily.com/rss/top.xml', topic: 'Scienza e salute' },
  { name: 'Nature', site: 'https://www.nature.com', feed: 'https://www.nature.com/nature.rss', topic: 'Ricerca scientifica' },
  { name: 'Focus', site: 'https://www.focus.it', feed: 'https://www.focus.it', topic: 'Scienza e cultura' },
  { name: 'Agenda Digitale', site: 'https://www.agendadigitale.eu', feed: 'https://www.agendadigitale.eu/feed/', topic: 'Digitale e società' },
  { name: 'GreenMe', site: 'https://www.greenme.it', feed: 'https://www.greenme.it/feed/', topic: 'Ambiente e benessere' },
  { name: 'Diritto.it', site: 'https://www.diritto.it', feed: 'https://www.diritto.it/feed/', topic: 'Diritto e giustizia' },
  { name: 'NASA · News', site: 'https://www.nasa.gov', feed: 'https://www.nasa.gov/feed/', topic: 'Spazio' },
  { name: 'Multiplayer.it', site: 'https://multiplayer.it', feed: 'https://multiplayer.it/feed/rss/homepage/', topic: 'Videogiochi' },
  { name: 'SpazioGames', site: 'https://www.spaziogames.it', feed: 'https://www.spaziogames.it/feed', topic: 'Videogiochi' },
  { name: 'Everyeye · Videogiochi', site: 'https://www.everyeye.it', feed: 'https://www.everyeye.it/feed/feed_news_rss.asp', topic: 'Videogiochi' },
  { name: 'Rock Paper Shotgun', site: 'https://www.rockpapershotgun.com', feed: 'https://www.rockpapershotgun.com/feed', topic: 'Videogiochi PC e indipendenti' },
  { name: 'Nintendo Life', site: 'https://www.nintendolife.com', feed: 'https://www.nintendolife.com/feeds/latest', topic: 'Nintendo' },
  { name: 'Push Square', site: 'https://www.pushsquare.com', feed: 'https://www.pushsquare.com/feeds/latest', topic: 'PlayStation' },
  { name: 'Xbox Wire', site: 'https://news.xbox.com', feed: 'https://news.xbox.com/en-us/feed/', topic: 'Xbox · fonte ufficiale' },
  { name: 'PlayStation Blog', site: 'https://blog.playstation.com', feed: 'https://blog.playstation.com/feed/', topic: 'PlayStation · fonte ufficiale' },
  { name: 'Tom’s Hardware · senza offerte', site: 'https://www.tomshw.it', feed: 'https://www.tomshw.it/feed/no-offerte', topic: 'Hardware e tecnologia' },
  { name: 'HDblog', site: 'https://www.hdblog.it', feed: 'https://www.hdblog.it/feed/', topic: 'Tecnologia e dispositivi' },
  { name: 'Engadget', site: 'https://www.engadget.com', feed: 'https://www.engadget.com/rss.xml', topic: 'Tecnologia e dispositivi' },
  { name: 'TechCrunch', site: 'https://techcrunch.com', feed: 'https://techcrunch.com/feed/', topic: 'Tecnologia e startup' },
  { name: 'BleepingComputer', site: 'https://www.bleepingcomputer.com', feed: 'https://www.bleepingcomputer.com/feed/', topic: 'Sicurezza informatica' },
  { name: 'The Hacker News', site: 'https://thehackernews.com', feed: 'https://feeds.feedburner.com/TheHackersNews', topic: 'Sicurezza informatica' },
  { name: 'TechPowerUp', site: 'https://www.techpowerup.com', feed: 'https://www.techpowerup.com/rss/news', topic: 'Hardware PC' },
  { name: 'Notebookcheck', site: 'https://www.notebookcheck.net', feed: 'https://www.notebookcheck.net/News.152.100.html', topic: 'Hardware e dispositivi' },
  { name: 'Unite.AI', site: 'https://www.unite.ai', feed: 'https://www.unite.ai/feed/', topic: 'IA e strumenti' },
  { name: 'OpenAI · News', site: 'https://openai.com/news', feed: 'https://openai.com/news/rss.xml', topic: 'IA · fonte ufficiale' },
  { name: 'Google Research', site: 'https://research.google', feed: 'https://research.google/blog/rss/', topic: 'IA e ricerca · fonte ufficiale' },
  { name: 'Google DeepMind', site: 'https://deepmind.google', feed: 'https://deepmind.google/blog/rss.xml', topic: 'IA e ricerca · fonte ufficiale' },
  { name: 'Microsoft Research', site: 'https://www.microsoft.com/en-us/research', feed: 'https://www.microsoft.com/en-us/research/feed/', topic: 'IA e ricerca · fonte ufficiale' },
  { name: 'NVIDIA Blog', site: 'https://blogs.nvidia.com', feed: 'https://blogs.nvidia.com/feed/', topic: 'IA e GPU · fonte ufficiale' },
  { name: 'Simon Willison', site: 'https://simonwillison.net', feed: 'https://simonwillison.net/atom/everything/', topic: 'IA pratica e modelli' },
  { name: 'The Decoder', site: 'https://the-decoder.com', feed: 'https://the-decoder.com/feed/', topic: 'IA · notizie e analisi' },
  { name: 'GamesIndustry.biz', site: 'https://www.gamesindustry.biz', feed: 'https://www.gamesindustry.biz/feed', topic: 'Industria dei videogiochi' },
] as const
