// Article-level matching: publisher names never determine a sector.
export const sectors = [
  { slug: 'ia', name: 'Intelligenza artificiale', description: 'Modelli, ricerca, strumenti e impatto dell’IA.', terms: 'intelligenza artificiale|artificial intelligence|machine learning|deep learning|generative ai|ai[- ](model[a-z]*|agent[a-z]*|tool[a-z]*|research|system[a-z]*|platform[a-z]*|startup[a-z]*|chip[a-z]*|safety|regulation|generated|powered)|generative|ia|llm|chatgpt|openai|anthropic|claude|deepmind|gemini|hugging face|copilot|gpt[- ]?[0-9a-z]*|modelli linguistici|reti neurali|neural network|diffusion model' },
  { slug: 'tecnologia', name: 'Tecnologia', description: 'Software, dispositivi, sicurezza e innovazione.', terms: 'tecnologi[a-z]*|technology|tech|software|hardware|smartphone|android|iphone|apple|microsoft|google|nvidia|intel|amd|computer|computing|cyber[a-z]*|malware|ransomware|hacker[a-z]*|sicurezza informatica|data breach|robot[a-z]*|chip[a-z]*|semiconduttor[a-z]*|semiconductor[a-z]*|openai|chatgpt|intelligenza artificiale|artificial intelligence|3d print[a-z]*|stampa 3d' },
  { slug: 'videogiochi', name: 'Videogiochi', description: 'Uscite, recensioni, console e industria del gaming.', terms: 'videogio[a-z]*|video game[a-z]*|gaming|gamer[a-z]*|gameplay|playstation|xbox|nintendo|steam|esport[a-z]*|ubisoft|rockstar|bethesda|capcom|elden ring|final fantasy|pokemon|pokémon|fortnite|minecraft|baldur|resident evil|call of duty|game pass|giochi (pc|console)|game (review|release|developer)|console' },
  { slug: 'diritto', name: 'Diritto e giustizia', description: 'Norme, sentenze, processo e sistema giudiziario.', terms: 'giustizia|diritto|giurisprudenza|cassazione|corte costituzionale|corte europea|corte d.appello|sentenz[a-z]*|tribunal[a-z]*|magistrat[a-z]*|avvocat[a-z]*|processo penal[a-z]*|codice penal[a-z]*|procedura penal[a-z]*|decreto legislativo|riforma (penale|della giustizia)|legal|judicial|law|lawsuit|(supreme|constitutional|criminal|federal|district|appeals|justice) court|court (ruling|case|decision|order)' },
  { slug: 'sicilia-catania', name: 'Sicilia e Catania', description: 'Cronaca e vita del territorio siciliano.', terms: 'sicilia[a-z]*|sicily|catania[a-z]*|palermo|messina|siracusa|ragusa|agrigento|caltanissetta|trapani|enna|etna|acireale|paternò|paterno|misterbianco|caltagirone|pozzallo|modica|gela|taormina|san giovanni la punta|san gregorio di catania' },
  { slug: 'politica', name: 'Politica', description: 'Governi, elezioni, istituzioni e relazioni internazionali.', terms: 'politic[a-z]*|govern[a-z]*|parlament[a-z]*|elezion[a-z]*|election[a-z]*|president[a-z]*|premier|minister[a-z]*|senat[a-z]*|congress[a-z]*|meloni|trump|putin|zelensk[a-z]*|netanyahu|nato|diplom[a-z]*|geopolitic[a-z]*|guerra|war|ucraina|ukraine|israel[a-z]*|iran|gaza' },
  { slug: 'economia', name: 'Economia', description: 'Mercati, imprese, lavoro e finanza.', terms: 'econom[a-z]*|finanz[a-z]*|financ[a-z]*|borsa|stock[a-z]*|market[a-z]*|inflazion[a-z]*|inflation|tass[a-z]*|tax[a-z]*|pension[a-z]*|stipend[a-z]*|salary|imprese|azienda[a-z]*|business|invest[a-z]*|pil|gdp|banc[a-z]*|bank[a-z]*|bitcoin|crypto[a-z]*|criptovalut[a-z]*|lavoro|occupazion[a-z]*|employment' },
  { slug: 'scienza', name: 'Scienza e salute', description: 'Ricerca, spazio, medicina e ambiente.', terms: 'scienz[a-z]*|scient[a-z]*|science|ricerca|research|fisica|physics|biolog[a-z]*|medicin[a-z]*|salute|health|cancro|cancer|tumor[a-z]*|covid|vaccin[a-z]*|disease[a-z]*|nasa|astronom[a-z]*|spazio|space|clima[a-z]*|climate|ambiente|environment[a-z]*|energia|energy|quantum|quantistic[a-z]*|nucleare|nuclear' },
  { slug: 'cultura', name: 'Cultura', description: 'Libri, cinema, musica, arte e società.', terms: 'cultur[a-z]*|cinema|film[a-z]*|movie[a-z]*|serie tv|television|netflix|libro|libri|book[a-z]*|romanzo|novel|letteratur[a-z]*|literatur[a-z]*|museo|museum|mostra|exhibition|teatro|theatre|theater|musica|music|concert[a-z]*|anime|manga|fumett[a-z]*|comics|filosof[a-z]*|philosoph[a-z]*' },
] as const
export type Sector = typeof sectors[number]
export function getSector(slug: string) { return sectors.find(sector => sector.slug === slug) }
export function sectorPattern(sector: Sector) { return `(^|[^[:alnum:]_])(${sector.terms})([^[:alnum:]_]|$)` }
export function sectorExactPattern(sector: Sector) { return ['ia', 'tecnologia'].includes(sector.slug) ? '(^|[^[:alnum:]_])(AI|AGI)([^[:alnum:]_]|$)' : null }
export function classifyArticle(article: { title: string; excerpt?: string | null }) {
  const original = `${article.title} ${article.excerpt ?? ''}`
  const text = original.toLowerCase()
  return sectors.filter(sector => new RegExp(`(^|[^\\p{L}\\p{N}_])(${sector.terms})([^\\p{L}\\p{N}_]|$)`, 'u').test(text) || (['ia','tecnologia'].includes(sector.slug) && /\b(AI|AGI)\b/.test(original))).map(sector => sector.slug)
}
